modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "epichunt"
version = "${version}"
displayName = "Epic Hunt"
authors = "Witchkings"
description = '''
Epic Hunt! A survival focus fauna mod aimed to bring animals, fish, birds, and rideable mobs into a medieval setting. Brought to you by BruceTheRonin and Witchkings. Are you ready to hunt dangerous game or to tame new livestock and enjoy some relaxing fishing?
'''
#logoFile = ""

[[dependencies.epichunt]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.epichunt]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.epichunt]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"